ALTER TABLE vinyls ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE vinyls ADD COLUMN last_modified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE reviews ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE reviews ADD COLUMN last_modified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE labels ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE labels ADD COLUMN last_modified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE reviews 
SET 
    is_deleted = TRUE,
    last_modified = CURRENT_TIMESTAMP
WHERE
    review_id = 5;
    
UPDATE vinyls 
SET 
    is_deleted = TRUE,
    last_modified = CURRENT_TIMESTAMP
WHERE
    vinyl_id = 10;

